image: safe-registry.alfastrah.ru/docker:25.0.5-dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  ARTIFACT_NAME: tes-base-image

stages:
  - deploy

deploy_to_nexus:
  stage: deploy
  services:
    - name: safe-registry.alfastrah.ru/docker:25.0.5-dind
      alias: docker
  script:
    - docker login --username $NEXUS_REGISTRY_LOGIN --password $NEXUS_REGISTRY_PASSWORD $NEXUS_REGISTRY_URL
    - docker build -t $NEXUS_REGISTRY_URL/$ARTIFACT_NAME:latest -t $NEXUS_REGISTRY_URL/$ARTIFACT_NAME:tes -t $NEXUS_REGISTRY_URL/$ARTIFACT_NAME:$CI_COMMIT_TAG .
    - docker push -a $NEXUS_REGISTRY_URL/$ARTIFACT_NAME
  when: manual
  only:
    - tags